# Source local extra (private) settings specific to machine if it exists
[ -f ~/.zsh.local ] && source ~/.zsh.local

# shell integration -> https://iterm2.com/documentation-shell-integration.html
source ~/.iterm2_shell_integration.`basename $SHELL`

# Load personal prompt style before zsh
source ~/dotfiles-osx/shell/custome_prompt.sh

#just php iterm intefration and code snippets
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
  export PATH="$(which phpcs):$PATH"

if [ -f ~/.antigen/antigen.log ]; then
  # Load antigen
  source $(brew --prefix)/share/antigen/antigen.zsh
  echo "Loading antigen"

  antigen use oh-my-zsh

  # Plugins
  antigen bundle git
  antigen bundle git-flow
  antigen bundle git-extras
  antigen bundle command-not
  antigen bundle command-not-found
  antigen bundle history
  antigen bundle brew
  antigen bundle osx

  # colors
  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-syntax-highlighting-filetypes
  antigen bundle colored-man-pages

  antigen bundle zsh-autosuggestions
  antigen bundle lukechilds/zsh-better-npm-completion
  antigen bundle unixorn/autoupdate-antigen.zshplugin
  antigen bundle gnu-utils
  antigen bundle autojump

  # Completions
  antigen bundle common-aliases
  antigen bundle compleat
  antigen bundle mollifier/anyframe
  antigen bundle zsh-users/zsh-completions src
  antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh
  antigen bundle djui/alias-tips
  antigen bundle z

  antigen bundle lein

  # Load the theme.
  antigen theme caiogondim/bullet-train-oh-my-zsh-theme bullet-train

  # Tell antigen that you're done.
  antigen apply

else

  # Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

  ZSH_THEME="wedisagree"

  plugins=(git mvn z sudo adb gradle git-extras)
  plugins+=(zsh-completions)
  autoload -U compinit && compinit # You should make sure $(compaudit) directories are owned by you and have 775 premissions

  if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
  fi

  source $ZSH/oh-my-zsh.sh

fi

# Hook function which gets executed right before shell prints prompt showing battery power.
function precmd() {
  local bottom_right=$(printf '$(battery)')
  RPROMPT=$bottom_right
}


# Load the shell dotfiles
for file in $HOME/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;


#phpbrew
  export PATH="/usr/local/bin/phpbrew:$PATH"
  [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc

#wp-cli completions
  fpath=(/usr/local/share/zsh-cometions $fpath)

# Python with virtualenvwrapper
# https://virtualenvwrapper.readthedocs.io/en/latest/install.html#python-versions
  if [ -f /Users/amit/Library/Python/2.7/bin/virtualenvwrapper.sh ]; then
    source /Users/amit/Library/Python/2.7/bin/virtualenvwrapper.sh
  fi
  
# Pyenv
  eval "$(pyenv init -)"

# env vars for tiny-care-terminal - from https://github.com/notwaldorf/tiny-care-terminal
  source ~/dotfiles-osx/shell/tiny-care.env

# heroku autocomplete setup
  export HEROKU_AC_ZSH_SETUP_PATH=/Users/amit/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;

# thefuck https://github.com/nvbn/thefuck
  eval $(thefuck --alias)