if [ -f ~/.antigen/antigen.log ]; then
  # Load antigen
  source $(brew --prefix)/share/antigen/antigen.zsh
  echo "Loading antigen"

  antigen use oh-my-zsh

  # Plugins
  antigen bundle git
  antigen bundle git-flow
  antigen bundle git-extras
  antigen bundle command-not
  antigen bundle command-not-found
  antigen bundle history
  antigen bundle brew
  antigen bundle osx

  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-autosuggestions
  antigen bundle lukechilds/zsh-better-npm-completion
  # antigen bundle unixorn/autoupdate-antigen.zshplugin
  antigen bundle gnu-utils
  antigen bundle autojump
  antigen bundle colored-man-pages

  # Completions
  antigen bundle common-aliases
  antigen bundle compleat
  antigen bundle mollifier/anyframe
  antigen bundle zsh-users/zsh-completions src
  antigen bundle zsh-users/zsh-history-substring-search ./zsh-history-substring-search.zsh
  antigen bundle djui/alias-tips
  antigen bundle z

  antigen bundle lein
  antigen bundle web-search


  # Load the theme.
  antigen theme caiogondim/bullet-train-oh-my-zsh-theme bullet-train

  # Tell antigen that you're done.
  antigen apply

else

  # Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

  # ZSH_THEME="candy"
  ZSH_THEME="wedisagree"

  plugins=(git mvn z sudo adb gradle git-extras)
  plugins+=(zsh-completions)
  autoload -U compinit && compinit

  if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
  fi

  source $ZSH/oh-my-zsh.sh

fi


# Directories to be prepended to $PATH
declare -a dirs_to_prepend
dirs_to_prepend=(
  "/usr/bin"
  "/usr/local/sbin"
  "/usr/local/git/bin"
  "/usr/local"
  "/usr/local/mysql/bin"
  "/sw/bin"
  "$HOME/dotfiles/bin"
  "$HOME/bin"
  "$HOME/.rvm/bin"
  "$(brew --prefix ruby)/bin"
  "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
  "$(brew --prefix)/share/npm/bin" # Add npm-installed package bin
)

# Explicitly configured $PATH
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

for dir in ${(k)dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="$PATH:${dir}"
  fi
done

unset dirs_to_prepend

export PATH



# User configuration

# Load the shell dotfiles
for file in $HOME/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Automatically list directory contents on `cd`.
auto-ls () {
   emulate -L zsh;
   # explicit sexy ls'ing as aliases arent honored in here.
   hash gls >/dev/null 2>&1 && CLICOLOR_FORCE=1 gls -aFh --color --group-directories-first || ls
 }
hpwd_functions=( auto-ls $chpwd_functions )

# Source local extra (private) settings specific to machine if it exists
[ -f ~/.zsh.local ] && source ~/.zsh.local

setopt EXTENDED_GLOB

# shell integration -> https://iterm2.com/documentation-shell-integration.html
source ~/.iterm2_shell_integration.`basename $SHELL`

# Add env.sh
  source ~/Projects/config/env.sh

#aliases for nginx php-fpm shit
  source ~/Projects/config/.service_aliases

# This loads nvm
  export NVM_DIR="/Users/amit/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

#just php iterm intefration and code snippets
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
  export PATH="$(which phpcs):$PATH"

#phpbrew
  export PATH="/usr/local/bin/phpbrew:$PATH"
  [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc

#wp-cli completions
  fpath=(/usr/local/share/zsh-cometions $fpath)

#brew
  export HOMEBREW_GITHUB_API_TOKEN="81e96387d9a1c7751da8b69b7be9e98f5673d979"
  export SSL_CERT_FILE="/etc/ssl/certs/cacert.pem"

#android studio path
  export ANDROID_HOME="$HOME/Library/Android/sdk"
  export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools


#yarn
  export PATH="$PATH:`yarn global bin`"

#else
  export PATH="/usr/local/sbin:$PATH"
  [[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn
  export PATH="/usr/local/opt/mongodb@3.2/bin:$PATH"

#pyhton + venvs
  export WORKON_HOME="$HOME/.virtualenvs"
  # export VIRTUALENVWRAPPER_PYTHON="/usr/local/lib/python2.7"
  # export PATH="$VIRTUALENVWRAPPER_PYTHON:$PATH"

# elastic search
export ES_HOME=~/apps/elasticsearch/elasticsearch-2.3.1
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_77/Contents/Home
export PATH=$ES_HOME/bin:$JAVA_HOME/bin:$PATH


#aliases for nginx php-fpm shit
  source ~/Projects/config/.service_aliases

# env vars for tiny-care-terminal - from https://github.com/notwaldorf/tiny-care-terminal
  source ~/dotfiles/shell/tiny-care.env
